Algoritmo "1.01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gelvazio Camargo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bryan R. Oechsler
// Data atual  : 27/07/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
            escreval("O primeiro programa a gente nunca esquece!")
            

Fimalgoritmo